правила :
  блок-нет-пустой : правда
  цвет-нет-недопустимый-шестнадцатеричный : правда
  font-family-no-duplicate-names : правда
  font-family-no-missing-generic-family-keyword : правда
  функция-расчет-нет-недействительный : истина
  функция-вычислить-без-без-оператора : истина
  функция-линейный-градиент-не-нестандартное-направление : истина
  строка без новой строки : правда
  unit-no-unknown : истина
  свойство-не-неизвестно : истина
  объявление-блок-без-дубликатов-свойств : истина
  комментарий-пустая-строка-перед :
    - всегда
    - игнорировать :
        - stylelint-команды
        - после комментария
  объявление-двоеточие-пробел-после : всегда
  декларация неважно : правда
  отступ :
    - 2
    - игнорировать :
        - внутренняя часть
  максимальное количество пустых строк : 2
  правило-пустая-строка-до :
    - всегда
    - кроме :
        - первый вложенный
      игнорировать :
        - после комментария
